---
- name: Install Docker
  hosts: all
  # by default become_user = root when we do become: yes
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        update_cache: yes
        state: present
    - name: Start docker daemon
      systemd:
        name: docker
        state: started

- name: Install Docker-compose
  hosts: all
  tasks:
    - name: Create docker-compose directory
      file:
        path: ~/.docker/cli-plugins
        state: directory
    - name: Get architecture of remote machine
      shell: uname -m
      register: remote_arch
    - name: Install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{lookup('pipe', 'uname -m')}}"
        dest: ~/.docker/cli-plugins/docker-compose
        mode: +x

- name: Add ec2-user to docker group
  hosts: all
  become: yes
  tasks: 
    - name: Add ec2-user to docker group
      user: 
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnect to server session
      meta: reset_connection

- name: Start docker containers
  hosts: docker_server
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker compose 
      copy:
        src: /---absolute_path----/docker-compose-full.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: Docker login
      docker_login:
        username: prashzan  # docker hub username
        password: "{{docker_password}}"
    - name: Start containers from compose
      community.docker.docker_compose_v2:
        project_src: /home/ec2-user



# - name: Test docker pull
#   hosts: docker_server
#   tasks:
#     - name: Pull redis
#       docker_image:
#         name: redis 
#         source: pull

